module.exports = [
    {repo: 'ui-base', main: 'base'},
    {repo: 'ui-calendar', main: 'calendar'},
    {repo: 'ui-chart', main: 'chart'},
    {repo: 'ui-drag', main: 'draggable'},
    {repo: 'ui-field', main: 'field'},
    {repo: 'ui-gotop', main: 'gotop'},
    {repo: 'ui-listview', main: 'listView'},
    {repo: 'ui-menu', main: 'menu'},
    {repo: 'ui-modal', main: 'modal'},
    {repo: 'ui-overlay', main: 'overlay'},
    {repo: 'ui-pager', main: 'pager'},
    {repo: 'ui-resizable', main: 'resizable'},
    {repo: 'ui-sample', main: 'sample'},
    {repo: 'ui-select', main: 'selectField'},
    {repo: 'ui-slider', main: 'slider'},
    {repo: 'ui-steps', main: 'steps'},
    {repo: 'ui-tabs', main: 'tabs'},
    {repo: 'ui-uploader', main: 'uploader'},
];
